"use client";
/* eslint-disable @next/next/no-img-element -- Supabase avatar hosts are runtime-configured. */
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, Check, ChevronRight, Pencil, Plus, Power, Search, UserRound, X } from "lucide-react";
import { ActionDialog } from "../shared/action-dialog";
import { getAdminProfessionalDetails, getAdminProfessionals, getAdminProfessionalServiceOptions, inviteAdminProfessional, updateAdminProfessional, type AdminProfessional, type AdminProfessionalDetails } from "../../lib/services/admin-professional-management-service";

const weekdays = ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];
const emptyDraft = { name: "", email: "", specialty: "", phone: "", bio: "", active: true, serviceIds: [] as string[] };
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function dateTime(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }

export function AdminProfessionalsSection({ createRequest = 0 }: { createRequest?: number }) {
  const previousCreateRequest = useRef(0);
  const [people, setPeople] = useState<AdminProfessional[]>([]), [services, setServices] = useState<Array<{ id: string; name: string }>>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [service, setService] = useState("all");
  const [selected, setSelected] = useState<AdminProfessional | null>(null), [details, setDetails] = useState<AdminProfessionalDetails | null>(null), [detailsLoading, setDetailsLoading] = useState(false);
  const [editTarget, setEditTarget] = useState<AdminProfessional | null>(null);
  const [formMode, setFormMode] = useState<"create" | "edit" | null>(null), [draft, setDraft] = useState(emptyDraft), [saving, setSaving] = useState(false), [confirming, setConfirming] = useState<AdminProfessional | null>(null);
  const opener = useRef<HTMLElement | null>(null), dialogRef = useRef<HTMLDivElement>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [items, options] = await Promise.all([getAdminProfessionals(), getAdminProfessionalServiceOptions()]); setPeople(items); setServices(options); } catch { setError("Não foi possível carregar as profissionais. Verifique sua sessão administrativa."); } finally { setLoading(false); } }, []);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  useEffect(() => {
    if (!selected) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setDetails(null);
    setDetailsLoading(true);
    getAdminProfessionalDetails(selected).then(setDetails).catch(() => setError("Não foi possível carregar os detalhes da profissional.")).finally(() => setDetailsLoading(false));
  }, [selected]);
  useEffect(() => { if (!selected && !formMode) return; const old = document.body.style.overflow; document.body.style.overflow = "hidden"; requestAnimationFrame(() => dialogRef.current?.focus()); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) closeOverlay(); }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = old; document.removeEventListener("keydown", key); }; });
  function closeOverlay() { setSelected(null); setEditTarget(null); setFormMode(null); setDetails(null); requestAnimationFrame(() => opener.current?.focus()); }
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase("pt-BR"); return people.filter((person) => (!term || `${person.name} ${person.specialty}`.toLocaleLowerCase("pt-BR").includes(term)) && (status === "all" || String(person.active) === status) && (service === "all" || person.services.some((item) => item.id === service))); }, [people, search, status, service]);
  function openCreate(event?: React.MouseEvent<HTMLButtonElement>) { if (event) opener.current = event.currentTarget; setEditTarget(null); setDraft(emptyDraft); setFormMode("create"); setError(""); }
  useEffect(() => { if (createRequest === previousCreateRequest.current) return; previousCreateRequest.current = createRequest; openCreate(); }, [createRequest]);
  function openEdit(person: AdminProfessional, element?: HTMLElement) { opener.current = element || opener.current; setEditTarget(person); setDraft({ name: person.name, email: person.email || "", specialty: person.specialty, phone: person.phone || "", bio: person.bio || "", active: person.active, serviceIds: person.services.filter((item) => item.active).map((item) => item.id) }); setSelected(null); setFormMode("edit"); }
  async function submit(event: FormEvent) { event.preventDefault(); const name = draft.name.trim().replace(/\s+/g, " "), specialty = draft.specialty.trim().replace(/\s+/g, " "), email = draft.email.trim().toLowerCase(); if (name.length < 3 || specialty.length < 2 || (formMode === "create" && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) { setError("Preencha nome, e-mail válido e especialidade."); return; } setSaving(true); setError(""); try { if (formMode === "create") await inviteAdminProfessional({ ...draft, name, email, specialty }); else if (editTarget) await updateAdminProfessional(editTarget.id, editTarget.profileId, { name, specialty, phone: draft.phone, bio: draft.bio, active: draft.active }); closeOverlay(); setNotice(formMode === "create" ? "Convite enviado e profissional cadastrada." : "Profissional atualizada com sucesso."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar a profissional."); } finally { setSaving(false); } }
  async function toggleStatus() { if (!confirming) return; setSaving(true); try { await updateAdminProfessional(confirming.id, confirming.profileId, { name: confirming.name, specialty: confirming.specialty, active: !confirming.active }); setConfirming(null); setNotice(confirming.active ? "Profissional desativada sem alterar o histórico." : "Profissional ativada."); await load(); } catch { setError("Não foi possível alterar o status da profissional."); } finally { setSaving(false); } }
  return <div className="admin-professionals-section">
    <div className="screen-top"><div><h2>Sua equipe</h2><p>Cadastre profissionais e acompanhe serviços e disponibilidade reais.</p></div><button className="primary button-with-icon" onClick={openCreate}><Plus aria-hidden="true"/> Nova profissional</button></div>
    <div className="table-filters professional-filters"><label><Search aria-hidden="true"/><span className="sr-only">Buscar por nome ou especialidade</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar nome ou especialidade"/></label><select aria-label="Filtrar por status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos os status</option><option value="true">Ativas</option><option value="false">Inativas</option></select><select aria-label="Filtrar por serviço" value={service} onChange={(e) => setService(e.target.value)}><option value="all">Todos os serviços</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    {notice && <div className="admin-data-message admin-data-message--success"><Check aria-hidden="true"/> {notice}</div>}{error && <div className="admin-data-message admin-data-message--error">{error}</div>}
    {loading ? <div className="admin-data-message">Carregando profissionais...</div> : filtered.length === 0 ? <div className="admin-empty-state"><UserRound aria-hidden="true"/><h3>Nenhuma profissional encontrada</h3><p>Ajuste os filtros ou cadastre uma nova profissional.</p></div> : <><div className="admin-results-count">{filtered.length} {filtered.length === 1 ? "profissional encontrada" : "profissionais encontradas"}</div><div className="professional-cards">{filtered.map((person) => <article key={person.id} className={!person.active ? "professional-card--inactive" : ""}><div className="big-avatar">{person.avatarUrl ? <img src={person.avatarUrl} alt=""/> : initials(person.name)}</div><span className={`professional-status ${person.availableToday ? "online" : "offline"}`}>{person.availableToday ? "Disponível hoje" : person.active ? "Indisponível hoje" : "Inativa"}</span><h3>{person.name}</h3><p>{person.specialty}</p>{person.email && <small className="professional-email">{person.email}</small>}<div className="mini-stats"><span><b>{person.appointmentsToday}</b> hoje</span><span><b>{person.appointmentsThisMonth}</b> no mês</span><span><b>{person.activeServices}</b> serviços</span></div><div className="skill-tags">{person.services.filter((x) => x.active).slice(0, 4).map((item) => <span key={item.id}>{item.name}</span>)}{person.activeServices === 0 && <span>Nenhum serviço ativo</span>}</div><div className="professional-card-actions"><button onClick={(e) => { opener.current = e.currentTarget; setSelected(person); }}><CalendarDays aria-hidden="true"/> Ver agenda e perfil <ChevronRight aria-hidden="true"/></button><button className="icon-button" aria-label={`Editar ${person.name}`} title="Editar" onClick={(e) => openEdit(person, e.currentTarget)}><Pencil aria-hidden="true"/></button><button className="icon-button" aria-label={`${person.active ? "Desativar" : "Ativar"} ${person.name}`} title={person.active ? "Desativar" : "Ativar"} onClick={() => setConfirming(person)}><Power aria-hidden="true"/></button></div></article>)}</div></>}
    {(selected || formMode) && <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget && !saving) closeOverlay(); }}><div className="professional-dialog" ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="professional-dialog-title"><button className="modal-close icon-button" onClick={closeOverlay} aria-label="Fechar"><X aria-hidden="true"/></button>{formMode ? <form onSubmit={submit}><span className="eyebrow">{formMode === "create" ? "NOVA PROFISSIONAL" : "EDITAR PROFISSIONAL"}</span><h2 id="professional-dialog-title">{formMode === "create" ? "Convidar profissional" : "Dados profissionais"}</h2><div className="professional-form-grid"><label><span>Nome completo *</span><input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} disabled={saving}/></label>{formMode === "create" && <label><span>E-mail *</span><input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} disabled={saving}/></label>}<label><span>Especialidade *</span><input value={draft.specialty} onChange={(e) => setDraft({ ...draft, specialty: e.target.value })} disabled={saving}/></label><label><span>Telefone</span><input value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} disabled={saving}/></label>{formMode === "edit" && <label className="wide"><span>Biografia</span><textarea value={draft.bio} onChange={(e) => setDraft({ ...draft, bio: e.target.value })} disabled={saving}/></label>}<label className="professional-active"><input type="checkbox" checked={draft.active} onChange={(e) => setDraft({ ...draft, active: e.target.checked })}/> Profissional ativa</label>{formMode === "create" && <fieldset className="wide"><legend>Serviços iniciais (opcional)</legend>{services.map((item) => <label className="professional-service-check" key={item.id}><input type="checkbox" checked={draft.serviceIds.includes(item.id)} onChange={(e) => setDraft({ ...draft, serviceIds: e.target.checked ? [...draft.serviceIds, item.id] : draft.serviceIds.filter((id) => id !== item.id) })}/>{item.name}</label>)}</fieldset>}</div>{error && <p className="form-error">{error}</p>}<footer><button type="button" onClick={closeOverlay} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "Salvando..." : formMode === "create" ? "Enviar convite" : "Salvar alterações"}</button></footer></form> : <ProfessionalDetails details={details} loading={detailsLoading} onEdit={() => details && openEdit(details)}/>}</div></div>}
    <ActionDialog open={Boolean(confirming)} title={confirming?.active ? "Desativar profissional?" : "Ativar profissional?"} description={confirming?.active ? `${confirming.name} deixará de aparecer em novos agendamentos. ${confirming.upcomingCount} próximo(s) atendimento(s), pagamentos e todo o histórico permanecerão preservados.` : `${confirming?.name || "A profissional"} voltará a ficar disponível para novos agendamentos conforme serviços e horários configurados.`} confirmLabel={confirming?.active ? "Desativar" : "Ativar"} danger={confirming?.active} loading={saving} onCancel={() => setConfirming(null)} onConfirm={() => void toggleStatus()}/>
  </div>;
}

function ProfessionalDetails({ details, loading, onEdit }: { details: AdminProfessionalDetails | null; loading: boolean; onEdit: () => void }) {
  if (loading || !details) return <div className="admin-data-message">Carregando perfil e agenda...</div>;
  return <div><span className="eyebrow">PERFIL PROFISSIONAL</span><h2 id="professional-dialog-title">{details.name}</h2><p>{details.specialty} · {details.active ? "Ativa" : "Inativa"}</p><button className="button button--outline button-with-icon" onClick={onEdit}><Pencil aria-hidden="true"/> Editar dados</button><div className="professional-detail-grid"><section><h3>Contato</h3><p>{details.email || "E-mail não disponível"}</p><p>{details.phone || "Telefone não informado"}</p></section><section><h3>Serviços vinculados</h3>{details.services.length ? details.services.map((x) => <p key={x.id}>{x.name} {x.active ? "" : "(inativo)"}</p>) : <p>Nenhum serviço vinculado.</p>}</section><section><h3>Disponibilidade semanal</h3>{details.availability.length ? details.availability.map((x) => <p key={x.id}>{weekdays[x.weekday]}: {x.active ? `${x.startTime}–${x.endTime}` : "inativa"}</p>) : <p>Nenhuma regra cadastrada.</p>}</section><section><h3>Próximos atendimentos</h3>{details.upcomingAppointments.length ? details.upcomingAppointments.map((x) => <p key={x.id}><b>{dateTime(x.startAt)}</b><br/>{x.clientName} · {x.serviceName}</p>) : <p>Nenhum próximo atendimento.</p>}</section><section><h3>Bloqueios futuros</h3>{details.futureBlocks.length ? details.futureBlocks.map((x) => <p key={x.id}>{dateTime(x.startAt)}–{dateTime(x.endAt)}{x.reason ? ` · ${x.reason}` : ""}</p>) : <p>Nenhum bloqueio futuro.</p>}</section><section><h3>Notificações</h3>{details.notificationPreferences ? <p>E-mail: {details.notificationPreferences.email ? "sim" : "não"}<br/>WhatsApp: {details.notificationPreferences.whatsapp ? "sim" : "não"}<br/>No app: {details.notificationPreferences.inApp ? "sim" : "não"}</p> : <p>Preferências não disponíveis.</p>}</section></div></div>;
}
